version: '3.8'

services:
  backend1:
    build:
      context: ./backend1
    container_name: backend1
    ports:
      - "5001:5001"

  backend2:
    build:
      context: ./backend2
    container_name: backend2
    ports:
      - "5002:5002"

  reverse_proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2